source 'https://buscarini@bitbucket.org/buscarini/jmspods.git'
source 'https://github.com/CocoaPods/Specs.git'

target 'JMSLogger', :exclusive => true do
  pod "JMSLogger", :path => "../"
end

target 'Tests', :exclusive => true do
	#pod "JMSLogger", :path => "../"
	
	#pod 'Realm.Headers'

  pod 'Specta', '~> 0.2.1'
  pod 'Expecta'
end
